name: Selenium Java TestNG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Optional: If you need to serve local HTML
    - name: Start local server for localhost testing
      run: python -m http.server 8080 &
    
    - name: Wait for server to be ready
      run: |
        for i in {1..10}; do
          curl -sSf http://localhost:8080/index.html && break
          echo "Waiting for server..."
          sleep 2
        done

    - name: Build and Run Tests with Maven
      run: mvn clean test

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ExtentReport
        path: '**/ExtentReport.html'

    - name: Upload CSV Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CricketScoreCSVLog
        path: '**/cricket_score_log.csv'
